// <auto-generated />
using System;
using MenuVoting.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuVoting.DataAccess.Migrations
{
    [DbContext(typeof(MenuVotingDbContext))]
    [Migration("20241123172951_changedRestaurantAndRegisterDtos")]
    partial class changedRestaurantAndRegisterDtos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuVoting.DataAccess.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PersonName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpirationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("Components")
                        .HasColumnType("text[]");

                    b.Property<Guid>("MenuPoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MenuPoolId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.MenuPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuPools");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("UserId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Identity.ApplicationUser", b =>
                {
                    b.HasOne("MenuVoting.DataAccess.Models.Restaurant", "Restaurant")
                        .WithMany("Users")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.Menu", b =>
                {
                    b.HasOne("MenuVoting.DataAccess.Models.MenuPool", "MenuPool")
                        .WithMany("Menus")
                        .HasForeignKey("MenuPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuPool");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.MenuPool", b =>
                {
                    b.HasOne("MenuVoting.DataAccess.Models.Restaurant", "Restaurant")
                        .WithMany("MenuPools")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.Vote", b =>
                {
                    b.HasOne("MenuVoting.DataAccess.Models.Menu", "Menu")
                        .WithMany("Votes")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuVoting.DataAccess.Identity.ApplicationUser", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.Menu", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.MenuPool", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("MenuVoting.DataAccess.Models.Restaurant", b =>
                {
                    b.Navigation("MenuPools");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
